DEFAULT_MAKE_DIR=/opt/pzsdk.ver4.0/make
PZC_TARGET_ARCH=sc1-64
TARGET=solver.pz
PZCSRC = ../pzc/solver.pzc ../pzc/board.pzc
CLANG_OPT=-O3 -std=c++14 -Wall -Wextra
vpath %.pzc ../pzc
include $(DEFAULT_MAKE_DIR)/default_pzcl_kernel.mk
